DROP TABLE  IF EXISTS  Users;

CREATE TABLE Users(
  Username VARCHAR(50) BINARY,
  Password VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  DEPARTMENT VARCHAR(50) NOT NULL,
  ROLE VARCHAR(50) NOT NULL,
  CONSTRAINT pl_pk
  PRIMARY KEY (Username)
)ENGINE=InnoDB;