DROP TABLE IF EXISTS Solution;

CREATE TABLE Solution(
	S_Title VARCHAR(50) NOT NULL,
	Heading VARCHAR(50) NOT NULL,
	IsExternal Boolean NOT NULL,
	Creator VARCHAR(50) BINARY NOT NULL,
	ExpiredDate DATE NOT NULL,
	UploadDate DATE NOT NULL,
	Version DOUBLE NOT NULL,
	Customer VARCHAR(50) NOT NULL,
	Content TEXT NOT NULL,
	CONSTRAINT so_pk
	PRIMARY KEY (S_Title,Heading),
	CONSTRAINT so_fk
	FOREIGN KEY (Creator)
	REFERENCES Users(Username)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE = InnoDB;