DROP TABLE IF EXISTS Content;

CREATE TABLE Content(
	Title VARCHAR(50) NOT NULL,
	IsExternal VARCHAR(50) NOT NULL,
	Author VARCHAR(50) BINARY NOT NULL,
	ExpiredDate DATE NOT NULL,
	UploadDate DATE NOT NULL,
	Customer VARCHAR(50) NOT NULL,
	CONSTRAINT so_pk
	PRIMARY KEY (Title,IsExternal),
	CONSTRAINT so_fk
	FOREIGN KEY (Author)
	REFERENCES Users(Username)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE = InnoDB;