DROP TABLE IF EXISTS Template;

CREATE TABLE Template(
  Template_Name VARCHAR(255) NOT NULL,
  DocSrcPrefixLocation VARCHAR(255) NOT NULL,
  NextPartId VARCHAR(255) NOT NULL,
  DocSrcParent VARCHAR(255) NOT NULL,
  CoverImage VARCHAR(255) NOT NULL,
  CONSTRAINT te_pk
  PRIMARY KEY (Template_Name)
)ENGINE=InnoDB;